name: first workflow
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2  # Use the latest stable version
      - name: Read File
        run: cat ./hello.txt  # Ensure the file path is correct
